const countryDomains = [
  { country: 'Afghanistan', tld: '.af' },
  { country: 'Albania', tld: '.al' },
  { country: 'Algeria', tld: '.dz' },
  { country: 'Andorra', tld: '.ad' },
  { country: 'Angola', tld: '.ao' },
  { country: 'Argentina', tld: '.ar' },
  { country: 'Armenia', tld: '.am' },
  { country: 'Australia', tld: '.au' },
  { country: 'Austria', tld: '.at' },
  { country: 'Azerbaijan', tld: '.az' },
  { country: 'Bahamas', tld: '.bs' },
  { country: 'Bahrain', tld: '.bh' },
  { country: 'Bangladesh', tld: '.bd' },
  { country: 'Barbados', tld: '.bb' },
  { country: 'Belarus', tld: '.by' },
  { country: 'Belgium', tld: '.be' },
  { country: 'Belize', tld: '.bz' },
  { country: 'Benin', tld: '.bj' },
  { country: 'Bhutan', tld: '.bt' },
  { country: 'Bolivia', tld: '.bo' },
  { country: 'Bosnia and Herzegovina', tld: '.ba' },
  { country: 'Botswana', tld: '.bw' },
  { country: 'Brazil', tld: '.br' },
  { country: 'Brunei', tld: '.bn' },
  { country: 'Bulgaria', tld: '.bg' },
  { country: 'Burkina Faso', tld: '.bf' },
  { country: 'Burundi', tld: '.bi' },
  { country: 'Cabo Verde', tld: '.cv' },
  { country: 'Cambodia', tld: '.kh' },
  { country: 'Cameroon', tld: '.cm' },
  { country: 'Canada', tld: '.ca' },
  { country: 'Catalunia', tld: '.cat' },
  { country: 'Central African Republic', tld: '.cf' },
  { country: 'Chad', tld: '.td' },
  { country: 'Chile', tld: '.cl' },
  { country: 'China', tld: '.cn' },
  { country: 'Colombia', tld: '.co' },
  { country: 'Comoros', tld: '.km' },
  { country: 'Congo, Democratic Republic of the', tld: '.cd' },
  { country: 'Congo, Republic of the', tld: '.cg' },
  { country: 'Costa Rica', tld: '.cr' },
  { country: 'Croatia', tld: '.hr' },
  { country: 'Cuba', tld: '.cu' },
  { country: 'Cyprus', tld: '.cy' },
  { country: 'Czech Republic', tld: '.cz' },
  { country: 'Denmark', tld: '.dk' },
  { country: 'Djibouti', tld: '.dj' },
  { country: 'Dominica', tld: '.dm' },
  { country: 'Dominican Republic', tld: '.do' },
  { country: 'Ecuador', tld: '.ec' },
  { country: 'Egypt', tld: '.eg' },
  { country: 'El Salvador', tld: '.sv' },
  { country: 'Equatorial Guinea', tld: '.gq' },
  { country: 'Eritrea', tld: '.er' },
  { country: 'Estonia', tld: '.ee' },
  { country: 'Eswatini', tld: '.sz' },
  { country: 'Ethiopia', tld: '.et' },
  { country: 'Fiji', tld: '.fj' },
  { country: 'Finland', tld: '.fi' },
  { country: 'France', tld: '.fr' },
  { country: 'Gabon', tld: '.ga' },
  { country: 'Gambia', tld: '.gm' },
  { country: 'Georgia', tld: '.ge' },
  { country: 'Germany', tld: '.de' },
  { country: 'Ghana', tld: '.gh' },
  { country: 'Greece', tld: '.gr' },
  { country: 'Grenada', tld: '.gd' },
  { country: 'Guatemala', tld: '.gt' },
  { country: 'Guinea', tld: '.gn' },
  { country: 'Guinea-Bissau', tld: '.gw' },
  { country: 'Guyana', tld: '.gy' },
  { country: 'Haiti', tld: '.ht' },
  { country: 'Honduras', tld: '.hn' },
  { country: 'Hungary', tld: '.hu' },
  { country: 'Iceland', tld: '.is' },
  { country: 'India', tld: '.in' },
  { country: 'Indonesia', tld: '.id' },
  { country: 'Iran', tld: '.ir' },
  { country: 'Iraq', tld: '.iq' },
  { country: 'Ireland', tld: '.ie' },
  { country: 'Israel', tld: '.il' },
  { country: 'Italy', tld: '.it' },
  { country: 'Jamaica', tld: '.jm' },
  { country: 'Japan', tld: '.jp' },
  { country: 'Jordan', tld: '.jo' },
  { country: 'Kazakhstan', tld: '.kz' },
  { country: 'Kenya', tld: '.ke' },
  { country: 'Kiribati', tld: '.ki' },
  { country: 'Korea, North', tld: '.kp' },
  { country: 'Korea, South', tld: '.kr' },
  { country: 'Kosovo', tld: '.xk' },
  { country: 'Kuwait', tld: '.kw' },
  { country: 'Kyrgyzstan', tld: '.kg' },
  { country: 'Laos', tld: '.la' },
  { country: 'Latvia', tld: '.lv' },
  { country: 'Lebanon', tld: '.lb' },
  { country: 'Lesotho', tld: '.ls' },
  { country: 'Liberia', tld: '.lr' },
  { country: 'Libya', tld: '.ly' },
  { country: 'Liechtenstein', tld: '.li' },
  { country: 'Lithuania', tld: '.lt' },
  { country: 'Luxembourg', tld: '.lu' },
  { country: 'Madagascar', tld: '.mg' },
  { country: 'Malawi', tld: '.mw' },
  { country: 'Malaysia', tld: '.my' },
  { country: 'Maldives', tld: '.mv' },
  { country: 'Mali', tld: '.ml' },
  { country: 'Malta', tld: '.mt' },
  { country: 'Marshall Islands', tld: '.mh' },
  { country: 'Mauritania', tld: '.mr' },
  { country: 'Mauritius', tld: '.mu' },
  { country: 'Mexico', tld: '.mx' },
  { country: 'Micronesia', tld: '.fm' },
  { country: 'Moldova', tld: '.md' },
  { country: 'Monaco', tld: '.mc' },
  { country: 'Mongolia', tld: '.mn' },
  { country: 'Montenegro', tld: '.me' },
  { country: 'Morocco', tld: '.ma' },
  { country: 'Mozambique', tld: '.mz' },
  { country: 'Myanmar', tld: '.mm' },
  { country: 'Namibia', tld: '.na' },
  { country: 'Nauru', tld: '.nr' },
  { country: 'Nepal', tld: '.np' },
  { country: 'Netherlands', tld: '.nl' },
  { country: 'New Zealand', tld: '.nz' },
  { country: 'Nicaragua', tld: '.ni' },
  { country: 'Niger', tld: '.ne' },
  { country: 'Nigeria', tld: '.ng' },
  { country: 'North Macedonia', tld: '.mk' },
  { country: 'Norway', tld: '.no' },
  { country: 'Oman', tld: '.om' },
  { country: 'Pakistan', tld: '.pk' },
  { country: 'Palau', tld: '.pw' },
  { country: 'Palestine', tld: '.ps' },
  { country: 'Panama', tld: '.pa' },
  { country: 'Papua New Guinea', tld: '.pg' },
  { country: 'Paraguay', tld: '.py' },
  { country: 'Peru', tld: '.pe' },
  { country: 'Philippines', tld: '.ph' },
  { country: 'Poland', tld: '.pl' },
  { country: 'Portugal', tld: '.pt' },
  { country: 'Qatar', tld: '.qa' },
  { country: 'Romania', tld: '.ro' },
  { country: 'Russia', tld: '.ru' },
  { country: 'Rwanda', tld: '.rw' },
  { country: 'Saint Kitts and Nevis', tld: '.kn' },
  { country: 'Saint Lucia', tld: '.lc' },
  { country: 'Saint Vincent and the Grenadines', tld: '.vc' },
  { country: 'Samoa', tld: '.ws' },
  { country: 'San Marino', tld: '.sm' },
  { country: 'Sao Tome and Principe', tld: '.st' },
  { country: 'Saudi Arabia', tld: '.sa' },
  { country: 'Senegal', tld: '.sn' },
  { country: 'Serbia', tld: '.rs' },
  { country: 'Seychelles', tld: '.sc' },
  { country: 'Sierra Leone', tld: '.sl' },
  { country: 'Singapore', tld: '.sg' },
  { country: 'Slovakia', tld: '.sk' },
  { country: 'Slovenia', tld: '.si' },
  { country: 'Solomon Islands', tld: '.sb' },
  { country: 'Somalia', tld: '.so' },
  { country: 'South Africa', tld: '.za' },
  { country: 'South Sudan', tld: '.ss' },
  { country: 'Spain', tld: '.es' },
  { country: 'Sri Lanka', tld: '.lk' },
  { country: 'Sudan', tld: '.sd' },
  { country: 'Suriname', tld: '.sr' },
  { country: 'Sweden', tld: '.se' },
  { country: 'Switzerland', tld: '.ch' },
  { country: 'Syria', tld: '.sy' },
  { country: 'Taiwan', tld: '.tw' },
  { country: 'Tajikistan', tld: '.tj' },
  { country: 'Tanzania', tld: '.tz' },
  { country: 'Thailand', tld: '.th' },
  { country: 'Timor-Leste', tld: '.tl' },
  { country: 'Togo', tld: '.tg' },
  { country: 'Tonga', tld: '.to' },
  { country: 'Trinidad and Tobago', tld: '.tt' },
  { country: 'Tunisia', tld: '.tn' },
  { country: 'Turkey', tld: '.tr' },
  { country: 'Turkmenistan', tld: '.tm' },
  { country: 'Tuvalu', tld: '.tv' },
  { country: 'Uganda', tld: '.ug' },
  { country: 'Ukraine', tld: '.ua' },
  { country: 'United Arab Emirates', tld: '.ae' },
  { country: 'United Kingdom', tld: '.uk' },
  { country: 'United States', tld: '.us' },
  { country: 'Uruguay', tld: '.uy' },
  { country: 'Uzbekistan', tld: '.uz' },
  { country: 'Vanuatu', tld: '.vu' },
  { country: 'Vatican City', tld: '.va' },
  { country: 'Venezuela', tld: '.ve' },
  { country: 'Vietnam', tld: '.vn' },
  { country: 'Yemen', tld: '.ye' },
  { country: 'Zambia', tld: '.zm' },
  { country: 'Zimbabwe', tld: '.zw' }
];

function checkDomainExtension(url) {
  // Cria uma instância da URL
  const parsedUrl = new URL(url);
  // Obtém o host da URL
  const host = parsedUrl.hostname;
  // Divide o host pelo ponto (.) e pega o último item
  const tld = '.' + host.split('.').pop();
  // Procura a extensão no array e obtém o país correspondente
  const domainEntry = countryDomains.find(entry => entry.tld === tld);

  if (domainEntry && tld) {
    // Se a extensão for encontrada, exibe o país no console e retorna false
    const domainInfo = `[!] TLD ${tld} do país: ${domainEntry.country}`;
    return domainInfo;
  }
  // Se a extensão não for encontrada, retorna true
  return false;
} 
